TOKENIZER_PATH = ''
RAW_DATA_PATH = ''
VOCAB_SIZE = 50_000
MIN_FREQUENCY = 2
BOS_TOKEN = '[CLS]'
EOS_TOKEN = '[SEP]'
SEP_TOKEN = '[SEP]'
CLS_TOKEN = '[CLS]'
UNK_TOKEN = '[UNK]'
PAD_TOKEN = '[PAD]'
MASK_TOKEN = '[MASK]'
SPECIAL_TOKENS = [
    '[CLS]',
    '[SEP]',
    '[UNK]',
    '[PAD]',
    '[MASK]'
]
